---
name: build

on:
  pull_request:
    branches: [master]
  push:
    tags: ['v*']

permissions:
  contents: read
  packages: write

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      GH_FEED: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3
        with:
          versionSpec: '5.x'
      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3
      - name: Select package version
        id: pkgver
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "value=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
          else
            echo "value=${{ steps.gitversion.outputs.fullSemVer }}" >> "$GITHUB_OUTPUT"
          fi
      - name: Run build and publish
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          ARGS="--target Publish --version ${{ steps.pkgver.outputs.value }} --ghfeed \"$GH_FEED\" --ghtoken \"${{ secrets.GITHUB_TOKEN }}\""
          if [ "${{ github.ref }}" = 'refs/heads/master' ]; then
            ARGS="$ARGS --nugetkey \"$NUGET_API_KEY\""
          fi
          ./build.sh $ARGS
